<h1>Chapter 5 | Data Exercise #5 | <code>World Development Indicators</code> | Generalizing from Data</h1>


<h2>Introduction:</h2>
<p>In this notebook, you will find my notes and code for Chapter 5's <b>exercise 5</b> of the book <a href="https://gabors-data-analysis.com/">Data Analysis for Business, Economics, and Policy</a>, by Gábor Békés and Gábor Kézdi. The question was: 

<p>5. Download the most recent data from the world development indicators website on GDP per capita and CO2 emission per capita.
<p>Assignments:</p>
<ul>
    <li>Divide countries into two groups by their GDP per capita and calculate the average difference in CO2 emission per capita between the two groups.</li>
    <li>Use bootstrap to estimate its standard error. </li>
    <li>Create the appropriate 95% CI.</li>
    <li>Interpret the results.</li>
</ul>
<h2>1. Load the data</h2>

In [97]:
import os
import pandas as pd
import warnings
from datetime import datetime
from plotnine import *
import sys
import numpy as np
from scipy.stats import norm, sem
from numpy.random import choice
import wbgapi as wb
warnings.filterwarnings("ignore")

In [98]:
# Increase number of returned rows in pandas
pd.set_option("display.max_rows", 500)

In [99]:
# Current script folder
dirname = os.getcwd()

# Get location folders

data_out = f"{dirname}/da_data_exercises/ch05-generalizing_from_data/05-WDI_CO2_GDP/data/clean/"
output = f"{dirname}/da_data_exercises/ch05-generalizing_from_data/05-WDI_CO2_GDP/data/output/"
func = f"{dirname}/da_case_studies/ch00-tech_prep/"
sys.path.append(func)
paths = [data_out, output]

for path in paths:
    if not os.path.exists(path):
        os.makedirs(path)

In [100]:
# Import the prewritten helper functions 
from py_helper_functions import *

## 1.1 Download the most recent data from the world development indicators website on GDP per capita and CO2 emission per capita.
While we could use the World Bank's APIs, there are several tools developed by others that already did the heavy lifting and can make our life easier. `wbgapi` is one among many. Let's learn a bit about it and use it in our favor.

For now, let's play around with it.

In [101]:
help(wb)

Help on package wbgapi:

NAME
    wbgapi

DESCRIPTION
    wbgapi provides a comprehensive interface to the World Bank's data and
    metadata API with built-in pandas integration

PACKAGE CONTENTS
    __version__
    data
    economy
    economy_coder
    economy_metadata
    income
    lending
    region
    series
    series_metadata
    source
    time
    topic
    utils

CLASSES
    builtins.Exception(builtins.BaseException)
        APIError
            APIResponseError
        URLError
    builtins.dict(builtins.object)
        Coder
    builtins.object
        Featureset
        Metadata
        MetadataCollection

    class APIError(builtins.Exception)
     |  APIError(url, msg, code=None)
     |
     |  Method resolution order:
     |      APIError
     |      builtins.Exception
     |      builtins.BaseException
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __init__(self, url, msg, code=None)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  __str__(self)
     |      Return str(self).
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __weakref__
     |      list of weak references to the object
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from builtins.Exception:
     |
     |  __new__(*args, **kwargs) class method of builtins.Exception
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.BaseException:
     |
     |  __delattr__(self, name, /)
     |      Implement delattr(self, name).
     |
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |
     |  __reduce__(...)
     |      Helper for pickle.
     |
     |  __repr__(self, /)
     |      Return repr(self).
     |
     |  __setattr__(self, name, value, /)
     |      Implement setattr(self, name, value).
     |
     |  __setstate__(...)
     |
     |  add_note(...)
     |      Exception.add_note(note) --
     |      add a note to the exception
     |
     |  with_traceback(...)
     |      Exception.with_traceback(tb) --
     |      set self.__traceback__ to tb and return self.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from builtins.BaseException:
     |
     |  __cause__
     |      exception cause
     |
     |  __context__
     |      exception context
     |
     |  __dict__
     |
     |  __suppress_context__
     |
     |  __traceback__
     |
     |  args

    class APIResponseError(APIError)
     |  APIResponseError(url, msg)
     |
     |  This error indicates that the module didn't understand the response from the API.
     |  Either it couldn't parse the JSON (the API sometimes returns XML even when JSON is
     |  requested) or it doesn't recognize the json schema
     |
     |  Method resolution order:
     |      APIResponseError
     |      APIError
     |      builtins.Exception
     |      builtins.BaseException
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __init__(self, url, msg)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from APIError:
     |
     |  __str__(self)
     |      Return str(self).
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from APIError:
     |
     |  __weakref__
     |      list of weak references to the object
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from builtins.Exception:
     |
     |  __new__(*args, **kwargs) class method of builtins.Exception
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.BaseException:
     |
     |  __delattr__(self, name, /)
     |      Implement delattr(self, name).
     |
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |
     |  __reduce__(...)
     |      Helper for pickle.
     |
     |  __repr__(self, /)
     |      Return repr(self).
     |
     |  __setattr__(self, name, value, /)
     |      Implement setattr(self, name, value).
     |
     |  __setstate__(...)
     |
     |  add_note(...)
     |      Exception.add_note(note) --
     |      add a note to the exception
     |
     |  with_traceback(...)
     |      Exception.with_traceback(tb) --
     |      set self.__traceback__ to tb and return self.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from builtins.BaseException:
     |
     |  __cause__
     |      exception cause
     |
     |  __context__
     |      exception context
     |
     |  __dict__
     |
     |  __suppress_context__
     |
     |  __traceback__
     |
     |  args

    class Coder(builtins.dict)
     |  Class returned by coder if passed a list of terms
     |
     |  Method resolution order:
     |      Coder
     |      builtins.dict
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __repr__(self)
     |      Return repr(self).
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables
     |
     |  __weakref__
     |      list of weak references to the object
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.dict:
     |
     |  __contains__(self, key, /)
     |      True if the dictionary has the specified key, else False.
     |
     |  __delitem__(self, key, /)
     |      Delete self[key].
     |
     |  __eq__(self, value, /)
     |      Return self==value.
     |
     |  __ge__(self, value, /)
     |      Return self>=value.
     |
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |
     |  __getitem__(self, key, /)
     |      Return self[key].
     |
     |  __gt__(self, value, /)
     |      Return self>value.
     |
     |  __init__(self, /, *args, **kwargs)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  __ior__(self, value, /)
     |      Return self|=value.
     |
     |  __iter__(self, /)
     |      Implement iter(self).
     |
     |  __le__(self, value, /)
     |      Return self<=value.
     |
     |  __len__(self, /)
     |      Return len(self).
     |
     |  __lt__(self, value, /)
     |      Return self<value.
     |
     |  __ne__(self, value, /)
     |      Return self!=value.
     |
     |  __or__(self, value, /)
     |      Return self|value.
     |
     |  __reversed__(self, /)
     |      Return a reverse iterator over the dict keys.
     |
     |  __ror__(self, value, /)
     |      Return value|self.
     |
     |  __setitem__(self, key, value, /)
     |      Set self[key] to value.
     |
     |  __sizeof__(...)
     |      D.__sizeof__() -> size of D in memory, in bytes
     |
     |  clear(...)
     |      D.clear() -> None.  Remove all items from D.
     |
     |  copy(...)
     |      D.copy() -> a shallow copy of D
     |
     |  get(self, key, default=None, /)
     |      Return the value for key if key is in the dictionary, else default.
     |
     |  items(...)
     |      D.items() -> a set-like object providing a view on D's items
     |
     |  keys(...)
     |      D.keys() -> a set-like object providing a view on D's keys
     |
     |  pop(...)
     |      D.pop(k[,d]) -> v, remove specified key and return the corresponding value.
     |
     |      If the key is not found, return the default if given; otherwise,
     |      raise a KeyError.
     |
     |  popitem(self, /)
     |      Remove and return a (key, value) pair as a 2-tuple.
     |
     |      Pairs are returned in LIFO (last-in, first-out) order.
     |      Raises KeyError if the dict is empty.
     |
     |  setdefault(self, key, default=None, /)
     |      Insert key with a value of default if key is not in the dictionary.
     |
     |      Return the value for key if key is in the dictionary, else default.
     |
     |  update(...)
     |      D.update([E, ]**F) -> None.  Update D from dict/iterable E and F.
     |      If E is present and has a .keys() method, then does:  for k in E: D[k] = E[k]
     |      If E is present and lacks a .keys() method, then does:  for k, v in E: D[k] = v
     |      In either case, this is followed by: for k in F:  D[k] = F[k]
     |
     |  values(...)
     |      D.values() -> an object providing a view on D's values
     |
     |  ----------------------------------------------------------------------
     |  Class methods inherited from builtins.dict:
     |
     |  __class_getitem__(...)
     |      See PEP 585
     |
     |  fromkeys(iterable, value=None, /)
     |      Create a new dictionary with keys from iterable and values set to value.
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from builtins.dict:
     |
     |  __new__(*args, **kwargs) class method of builtins.dict
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from builtins.dict:
     |
     |  __hash__ = None

    class Featureset(builtins.object)
     |  Featureset(items, columns=None)
     |
     |  Methods defined here:
     |
     |  __init__(self, items, columns=None)
     |      can be initialized with any iterable
     |
     |  __repr__(self)
     |      Return repr(self).
     |
     |  table(self)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables
     |
     |  __weakref__
     |      list of weak references to the object

    class Metadata(builtins.object)
     |  Metadata(concept, id, name)
     |
     |  Methods defined here:
     |
     |  __init__(self, concept, id, name)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  __repr__(self)
     |      Return repr(self).
     |
     |  repr(self, q=None, padding=None)
     |      Same as __repr__ but includes formatting options
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables
     |
     |  __weakref__
     |      list of weak references to the object

    class MetadataCollection(builtins.object)
     |  MetadataCollection(brief=False, padding=80, q=None)
     |
     |  Methods defined here:
     |
     |  __init__(self, brief=False, padding=80, q=None)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  __repr__(self)
     |      Return repr(self).
     |
     |  append(self, meta)
     |      Append a Metadata object to our store
     |
     |  brief_table(self, tablefmt)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables
     |
     |  __weakref__
     |      list of weak references to the object

    class URLError(builtins.Exception)
     |  Method resolution order:
     |      URLError
     |      builtins.Exception
     |      builtins.BaseException
     |      builtins.object
     |
     |  Data descriptors defined here:
     |
     |  __weakref__
     |      list of weak references to the object
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.Exception:
     |
     |  __init__(self, /, *args, **kwargs)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from builtins.Exception:
     |
     |  __new__(*args, **kwargs) class method of builtins.Exception
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.BaseException:
     |
     |  __delattr__(self, name, /)
     |      Implement delattr(self, name).
     |
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |
     |  __reduce__(...)
     |      Helper for pickle.
     |
     |  __repr__(self, /)
     |      Return repr(self).
     |
     |  __setattr__(self, name, value, /)
     |      Implement setattr(self, name, value).
     |
     |  __setstate__(...)
     |
     |  __str__(self, /)
     |      Return str(self).
     |
     |  add_note(...)
     |      Exception.add_note(note) --
     |      add a note to the exception
     |
     |  with_traceback(...)
     |      Exception.with_traceback(tb) --
     |      set self.__traceback__ to tb and return self.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from builtins.BaseException:
     |
     |  __cause__
     |      exception cause
     |
     |  __context__
     |      exception context
     |
     |  __dict__
     |
     |  __suppress_context__
     |
     |  __traceback__
     |
     |  args

FUNCTIONS
    Series(data, key='id', value='value', name=None)
        Convert a list-like to a pandas Series object. This core function is
        called by several dimension-specific implementation functions.

        Arguments:
            data:       an object array, generator, or function that returns a list-like

            key:        field for the Series index

            value:      field for the Series column values

            name:       Series column name. If None, same as value

        Returns:
            a pandas Series object

        Example:
            Generally you are better off calling the Series function for a specific feature
            e.g., wbgapi.time.Series(). Direct calls should only be necessary for databases
            with custom dimensions, for instance:

            wbgapi.Series(wbgapi.source.features('version', db=57))

    abbreviate(text, q=None, padding=80)
        Returns a shortened version of the text string comprised of the search pattern
        and a specified number of characters on either side. This is used to optimize
        search results. If the search pattern

    fetch(url, params={}, concepts=False, lang=None)
        Iterate over an API request with automatic paging.  The API returns a
        variety of response structures depending on the endpoint. fetch() sniffs
        the response structure and return the most appropriate set of iterated objects.

        Arguments:
            url:        partial URL (minus the base URL and langage) for the API query, minus the query string

            params:     optional query string parameters (required defaults are supplied by the function)

            concepts:   pass True to return results at the concept level, as opposed to the element/variable level

            lang:       preferred language. Pass none to use the global default

        Returns:
            a generator object.

        Example:
            for row in wbgapi.data.fetch('countries'):
              print(row['id'], row['name'])

        Notes:
            For most use cases there are higher level functions that are easier and safer than
            calling fetch() directly. But it's still very useful for direct testing and discovery
            of the API.

    get(url, params={}, concepts=False, lang=None)
        Return a single response from the API

        Arguments:
            url:        full URL for the API query, minus the query string

            params:     optional query string parameters (required defaults are supplied by the function)

            concepts:   pass True to return a result at the concept level, as opposed to the element/variable level

        Returns:
            First row from the response

        Example:
            print(wbgapi.get('countries/BRA')['name'])

    htmlTable(*args, **kwargs)
        Generates an HTML table wrapped in a <div class="wbgapi"/> to allow users
        to customize the display if they wish. All arguments are passed to tabulate;
        you should not include the 'tablefmt=html' parameter

    metadata(url, variables, concepts='all', **kwargs)
        Return metadata records

        Arguments:
            url:        url with tokens, as per refetch()

            variables:  variables that can be chunked, in priority order (see refetch)

            concepts:   Name or list-like of the concepts to return: 'all' for all concepts

            **kwargs:   Remaining arguments to pass to refetch (must include varables for tokens in url)

        Returns:
            a generator that returns Metadata objects

        Example:
            for meta in wbgapi.metadata('sources/2/series/{series}/country/{economy}/metadata', ['series', 'economy'],
                concepts=['Series','Country-Series'], series='SP.POP.TOTL', economy='FRA;CAN'):
                    print(meta.concept, meta.id, len(meta.metadata))

        Notes:
            Each return from the generator will include a unique concept/id pair and a complete corresponding metadata record

    queryParam(arg, concept=None, db=None)
        Prepare parameters for an API query. This is a core function
        called by several dimension-specific functions of the same name

        Arguments:
            arg:        a record identifier or list-like of identifiers

            concept:    concept for the arguments passed

            db:         database; pass None to access the global database

        Returns:
            a semicolon separated API-ready parameter string

    reduce(...)
        reduce(function, iterable[, initial]) -> value

        Apply a function of two arguments cumulatively to the items of a sequence
        or iterable, from left to right, so as to reduce the iterable to a single
        value.  For example, reduce(lambda x, y: x+y, [1, 2, 3, 4, 5]) calculates
        ((((1+2)+3)+4)+5).  If initial is present, it is placed before the items
        of the iterable in the calculation, and serves as a default when the
        iterable is empty.

    refetch(url, variables, **kwargs)
        repeating fetch: provides a variation of fetch() that allows URLs that exceed the maximium API limit to
        be chunked.

        Arguments:
            url:            partial URL with tokens, each of which must have values specified as function arguments. See example below

            variables:      array of variables to be chunked if necessary, in the order they should be chunked

            **kwargs:       remaining arguments MUST include values for each token in the url string. All arguments to fetch
                            are also acceptable and are passed to fetch. Any "chunkable" variable should be a semicolon-separated
                            value array. Arrays and iterables are not acceptable values

        Returns:
            A generator object

        Example:
            # fetch all indicators for Brazil and Argentina

In [102]:
help(wb.series)

Help on module wbgapi.series in wbgapi:

NAME
    wbgapi.series - Access information about series in a database

FUNCTIONS
    Series(id='all', q=None, topic=None, db=None, name='SeriesName')
        Return a pandas Series by calling list

    get(id, db=None)
        Retrieve a specific series object

        Arguments:
            id:     the series identifier

            db:     database; pass None to access the global database

        Returns:
            a series object

        Example:
            print(wbgapi.series.get('SP.POP.TOTL')['value'])

    info(id='all', q=None, topic=None, db=None)
        Print a user report of series. This can be time consuming
        for large databases like the WDI if 'all' series are requested.

        Arguments:
            id:         a series identifier or list-like of identifiers

            q:          search string (on series name))

            topic:      topic ID or list-like

            db:         database; pass None to access the global database

        Returns:
            None

    list(id='all', q=None, topic=None, db=None)
        Return a list of series elements in the current database

        Arguments:
            id:     a series identifier (i.e., CETS code) or list-like

            q:      search string (on series name)

            topic:  topic ID or list-like

            db:     database; pass None to access the global database

        Returns:
            a generator object

        Example:
            for elem in wbgapi.series.list():
                print(elem['id'], elem['value'])

FILE
    c:\users\felip\workspace_personal\python_work\bk_data_analysis\.venv\lib\site-packages\wbgapi\series.py

In [103]:
wb.source.info()

id    name                                                                  code      concepts  lastupdated
----  --------------------------------------------------------------------  ------  ----------  -------------
1     Doing Business                                                        DBS              3  2021-08-18
2     World Development Indicators                                          WDI              3  2025-12-16
3     Worldwide Governance Indicators                                       WGI              3  2024-11-05
5     Subnational Malnutrition Database                                     SNM              3  2016-03-21
6     International Debt Statistics                                         IDS              4  2025-12-03
11    Africa Development Indicators                                         ADI              3  2013-02-22
12    Education Statistics                                                  EDS              3  2024-06-25
13    Enterprise Surveys                                                    ESY              3  2022-03-25
14    Gender Statistics                                                     GDS              3  2025-11-11
15    Global Economic Monitor                                               GEM              3  2025-12-17
16    Health Nutrition and Population Statistics                            HNP              3  2025-07-02
18    IDA Results Measurement System                                        IDA              3  2021-07-23
19    Millennium Development Goals                                          MDG              3  2018-09-19
20    Quarterly Public Sector Debt                                          PSD              3  2025-10-29
22    Quarterly External Debt Statistics SDDS                               QDS              3  2025-10-31
23    Quarterly External Debt Statistics GDDS                               QDG              3  2025-10-31
25    Jobs                                                                  JOB              3  2025-07-01
27    Global Economic Prospects                                             GEP              3  2025-06-10
28    Global Findex database                                                FDX              3  2025-10-06
29    The Atlas of Social Protection: Indicators of Resilience and Equity   GSP              3  2025-08-25
30    Exporter Dynamics Database – Indicators at Country-Year Level         ED1              3  2016-03-31
31    Country Policy and Institutional Assessment                           CPI              3  2025-07-12
32    Global Financial Development                                          GFD              3  2022-09-23
33    G20 Financial Inclusion Indicators                                    G2F              3  2019-02-27
34    Global Partnership for Education                                      GPE              3  2013-04-12
35    Sustainable Energy for All                                            SE4              3  2018-06-30
37    LAC Equity Lab                                                        LEL              3  2016-04-06
38    Subnational Poverty                                                   SNP              3  2015-04-27
39    Health Nutrition and Population Statistics by Wealth Quintile         HNQ              3  2022-12-13
40    Population estimates and projections                                  HPP              3  2025-12-17
41    Country Partnership Strategy for India (FY2013 - 17)                  CPS              3  2015-05-22
43    Adjusted Net Savings                                                  WAT              3  2023-06-08
45    Indonesia Database for Policy and Economic Research                   IDD              3  2022-08-11
46    Sustainable Development Goals                                         SDG              3  2022-07-22
50    Subnational Population                                                SNT              3  2017-09-21
54    Joint External Debt Hub                                               JED              3  2025-10-27
57    WDI Database Archives                                                 WDA              4  2025-10-29
58    Universal Health Coverage                                             UHC              3  2019-04-25
59    Wealth Accounts                                                       WAC              3  2024-10-08
60    Economic Fitness                                                      EFT              3  2018-04-19
61    PPPs Regulatory Quality                                               PRQ              3  2019-04-25
62    International Comparison Program (ICP) 2011                           ICP              4  2020-08-24
63    Human Capital Index                                                   HCI              3  2020-09-21
64    Worldwide Bureaucracy Indicators                                      WBI              3  2025-02-24
65    Health Equity and Financial Protection Indicators                     HPI              3  2019-11-06
66    Logistics Performance Index                                           LPI              3  2024-03-26
67    PEFA 2011                                                             PF1              4  2025-06-26
68    PEFA 2016                                                             PF6              4  2025-12-08
69    Global Financial Inclusion and Consumer Protection Survey             RFA              3  2019-06-27
70    Economic Fitness 2                                                    EF2              3  2024-11-30
71    International Comparison Program (ICP) 2005                           IC5              4  2021-09-10
73    Global Financial Inclusion and Consumer Protection Survey (Internal)  RFI              3  2019-06-27
75    Environment, Social and Governance (ESG) Data                         ESG              3  2025-07-30
76    Remittance Prices Worldwide (Sending Countries)                       RWS              3  2020-12-07
77    Remittance Prices Worldwide (Receiving Countries)                     RWR              3  2020-12-07
78    ICP 2017                                                              IC7              4  2020-10-21
79    PEFA_GRPFM                                                            GRP              4  2025-11-17
80    Gender Disaggregated Labor Database (GDLD)                            GDL              4  2020-07-25
81    International Debt Statistics: DSSI                                   DSI              4  2025-12-03
82    Global Public Procurement                                             GPP              3  2021-03-24
83    Statistical Performance Indicators (SPI)                              SPI              3  2024-11-11
84    Education Policy                                                      EDP              3  2024-10-03
85    PEFA_2021_SNG                                                         SNG              4  2025-10-24
86    Global Jobs Indicators Database (JOIN)                                JON              3  2023-05-22
87    Country Climate and Development Report (CCDR)                         CCD              3  2022-10-07
88    Food Prices for Nutrition                                             FPN              4  2025-07-31
89    Identification for Development (ID4D) Data                            ID4              3  2025-10-27
90    ICP 2021                                                              IC2              4  2024-08-04
91    PEFA_CRPFM                                                            CRP              4  2025-12-03
92    Disability Data Hub (DDH)                                             DDH              3  2025-03-28
93    FPN Datahub Archive                                                   FPA              4  2025-10-22
      71 elements

In [104]:
wb.series.info(db=2)

id                          value
--------------------------  ---------------------------------------------------------------------------------------------------------------------------------------------
AG.CON.FERT.PT.ZS           Fertilizer consumption (% of fertilizer production)
AG.CON.FERT.ZS              Fertilizer consumption (kilograms per hectare of arable land)
AG.LND.AGRI.K2              Agricultural land (sq. km)
AG.LND.AGRI.ZS              Agricultural land (% of land area)
AG.LND.ARBL.HA              Arable land (hectares)
AG.LND.ARBL.HA.PC           Arable land (hectares per person)
AG.LND.ARBL.ZS              Arable land (% of land area)
AG.LND.CREL.HA              Land under cereal production (hectares)
AG.LND.CROP.ZS              Permanent cropland (% of land area)
AG.LND.EL5M.RU.K2           Rural land area where elevation is below 5 meters (sq. km)
AG.LND.EL5M.RU.ZS           Rural land area where elevation is below 5 meters (% of total land area)
AG.LND.EL5M.UR.K2           Urban land area where elevation is below 5 meters (sq. km)
AG.LND.EL5M.UR.ZS           Urban land area where elevation is below 5 meters (% of total land area)
AG.LND.EL5M.ZS              Land area where elevation is below 5 meters (% of total land area)
AG.LND.FRST.K2              Forest area (sq. km)
AG.LND.FRST.ZS              Forest area (% of land area)
AG.LND.IRIG.AG.ZS           Agricultural irrigated land (% of total agricultural land)
AG.LND.PRCP.MM              Average precipitation in depth (mm per year)
AG.LND.TOTL.K2              Land area (sq. km)
AG.LND.TOTL.RU.K2           Rural land area (sq. km)
AG.LND.TOTL.UR.K2           Urban land area (sq. km)
AG.PRD.CREL.MT              Cereal production (metric tons)
AG.PRD.CROP.XD              Crop production index (2014-2016 = 100)
AG.PRD.FOOD.XD              Food production index (2014-2016 = 100)
AG.PRD.LVSK.XD              Livestock production index (2014-2016 = 100)
AG.SRF.TOTL.K2              Surface area (sq. km)
AG.YLD.CREL.KG              Cereal yield (kg per hectare)
BG.GSR.NFSV.GD.ZS           Trade in services (% of GDP)
BM.GSR.CMCP.ZS              Communications, computer, etc. (% of service imports, BoP)
BM.GSR.FCTY.CD              Primary income payments (BoP, current US$)
BM.GSR.GNFS.CD              Imports of goods and services (BoP, current US$)
BM.GSR.INSF.ZS              Insurance and financial services (% of service imports, BoP)
BM.GSR.MRCH.CD              Goods imports (BoP, current US$)
BM.GSR.NFSV.CD              Service imports (BoP, current US$)
BM.GSR.ROYL.CD              Charges for the use of intellectual property, payments (BoP, current US$)
BM.GSR.TOTL.CD              Imports of goods, services and primary income (BoP, current US$)
BM.GSR.TRAN.ZS              Transport services (% of service imports, BoP)
BM.GSR.TRVL.ZS              Travel services (% of service imports, BoP)
BM.KLT.DINV.CD.WD           Foreign direct investment, net outflows (BoP, current US$)
BM.KLT.DINV.WD.GD.ZS        Foreign direct investment, net outflows (% of GDP)
BM.TRF.PRVT.CD              Secondary income, other sectors, payments (BoP, current US$)
BM.TRF.PWKR.CD.DT           Personal remittances, paid (current US$)
BN.CAB.XOKA.CD              Current account balance (BoP, current US$)
BN.CAB.XOKA.GD.ZS           Current account balance (% of GDP)
BN.FIN.TOTL.CD              Net financial account (BoP, current US$)
BN.GSR.FCTY.CD              Net primary income (BoP, current US$)
BN.GSR.GNFS.CD              Net trade in goods and services (BoP, current US$)
BN.GSR.MRCH.CD              Net trade in goods (BoP, current US$)
BN.KAC.EOMS.CD              Net errors and omissions (BoP, current US$)
BN.KLT.DINV.CD              Foreign direct investment, net (BoP, current US$)
BN.KLT.PTXL.CD              Portfolio investment, net (BoP, current US$)
BN.RES.INCL.CD              Reserves and related items (BoP, current US$)
BN.TRF.CURR.CD              Net secondary income (BoP, current US$)
BN.TRF.KOGT.CD              Net capital account (BoP, current US$)
BX.GRT.EXTA.CD.WD           Grants, excluding technical cooperation (BoP, current US$)
BX.GRT.TECH.CD.WD           Technical cooperation grants (BoP, current US$)
BX.GSR.CCIS.CD              ICT service exports (BoP, current US$)
BX.GSR.CCIS.ZS              ICT service exports (% of service exports, BoP)
BX.GSR.CMCP.ZS              Communications, computer, etc. (% of service exports, BoP)
BX.GSR.FCTY.CD              Primary income receipts (BoP, current US$)
BX.GSR.GNFS.CD              Exports of goods and services (BoP, current US$)
BX.GSR.INSF.ZS              Insurance and financial services (% of service exports, BoP)
BX.GSR.MRCH.CD              Goods exports (BoP, current US$)
BX.GSR.NFSV.CD              Service exports (BoP, current US$)
BX.GSR.ROYL.CD              Charges for the use of intellectual property, receipts (BoP, current US$)
BX.GSR.TOTL.CD              Exports of goods, services and primary income (BoP, current US$)
BX.GSR.TRAN.ZS              Transport services (% of service exports, BoP)
BX.GSR.TRVL.ZS              Travel services (% of service exports, BoP)
BX.KLT.DINV.CD.WD           Foreign direct investment, net inflows (BoP, current US$)
BX.KLT.DINV.WD.GD.ZS        Foreign direct investment, net inflows (% of GDP)
BX.PEF.TOTL.CD.WD           Portfolio equity, net inflows (BoP, current US$)
BX.TRF.CURR.CD              Secondary income receipts (BoP, current US$)
BX.TRF.PWKR.CD              Personal transfers, receipts (BoP, current US$)
BX.TRF.PWKR.CD.DT           Personal remittances, received (current US$)
BX.TRF.PWKR.DT.GD.ZS        Personal remittances, received (% of GDP)
CC.EST                      Control of Corruption: Estimate
CC.NO.SRC                   Control of Corruption: Number of Sources
CC.PER.RNK                  Control of Corruption: Percentile Rank
CC.PER.RNK.LOWER            Control of Corruption: Percentile Rank, Lower Bound of 90% Confidence Interval
CC.PER.RNK.UPPER            Control of Corruption: Percentile Rank, Upper Bound of 90% Confidence Interval
CC.STD.ERR                  Control of Corruption: Standard Error
CM.MKT.INDX.ZG              S&P Global Equity Indices (annual % change)
CM.MKT.LCAP.CD              Market capitalization of listed domestic companies (current US$)
CM.MKT.LCAP.GD.ZS           Market capitalization of listed domestic companies (% of GDP)
CM.MKT.LDOM.NO              Listed domestic companies, total
CM.MKT.TRAD.CD              Stocks traded, total value (current US$)
CM.MKT.TRAD.GD.ZS           Stocks traded, total value (% of GDP)
CM.MKT.TRNR                 Stocks traded, turnover ratio of domestic shares (%)
DC.DAC.AUSL.CD              Net bilateral aid flows from DAC donors, Australia (current US$)
DC.DAC.AUTL.CD              Net bilateral aid flows from DAC donors, Austria (current US$)
DC.DAC.BELL.CD              Net bilateral aid flows from DAC donors, Belgium (current US$)
DC.DAC.CANL.CD              Net bilateral aid flows from DAC donors, Canada (current US$)
DC.DAC.CECL.CD              Net bilateral aid flows from DAC donors, European Union institutions (current US$)
DC.DAC.CHEL.CD              Net bilateral aid flows from DAC donors, Switzerland (current US$)
DC.DAC.CZEL.CD              Net bilateral aid flows from DAC donors, Czechia (current US$)
DC.DAC.DEUL.CD              Net bilateral aid flows from DAC donors, Germany (current US$)
DC.DAC.DNKL.CD              Net bilateral aid flows from DAC donors, Denmark (current US$)
DC.DAC.ESPL.CD              Net bilateral aid flows from DAC donors, Spain (current US$)
DC.DAC.ESTL.CD              Net bilateral aid flows from DAC donors, Estonia (current US$)
DC.DAC.FINL.CD              Net bilateral aid flows from DAC donors, Finland (current US$)
DC.DAC.FRAL.CD              Net bilateral aid flows from DAC donors, France (current US$)
DC.DAC.GBRL.CD              Net bilateral aid flows from DAC donors, United Kingdom (current US$)
DC.DAC.GRCL.CD              Net bilateral aid flows from DAC donors, Greece (current US$)
DC.DAC.HUNL.CD              Net bilateral aid flows from DAC donors, Hungary (current US$)
DC.DAC.IRLL.CD              Net bilateral aid flows from DAC donors, Ireland (current US$)
DC.DAC.ISLL.CD              Net bilateral aid flows from DAC donors, Iceland (current US$)
DC.DAC.ITAL.CD              Net bilateral aid flows from DAC donors, Italy (current US$)
DC.DAC.JPNL.CD              Net bilateral aid flows from DAC donors, Japan (current US$)
DC.DAC.KORL.CD              Net bilateral aid flows from DAC donors, Korea, Rep. (current US$)
DC.DAC.LTUL.CD              Net bilateral aid flows from DAC donors, Lithuania (current US$)
DC.DAC.LUXL.CD              Net bilateral aid flows from DAC donors, Luxembourg (current US$)
DC.DAC.NLDL.CD              Net bilateral aid flows from DAC donors, Netherlands (current US$)
DC.DAC.NORL.CD              Net bilateral aid flows from DAC donors, Norway (current US$)
DC.DAC.NZLL.CD              Net bilateral aid flows from DAC donors, New Zealand (current US$)
DC.DAC.POLL.CD              Net bilateral aid flows from DAC donors, Poland (current US$)
DC.DAC.PRTL.CD              Net bilateral aid flows from DAC donors, Portugal (current US$)
DC.DAC.SVKL.CD              Net bilateral aid flows from DAC donors, Slovak Republic (current US$)
DC.DAC.SVNL.CD              Net bilateral aid flows from DAC donors, Slovenia (current US$)
DC.DAC.SWEL.CD              Net bilateral aid flows from DAC donors, Sweden (current US$)
DC.DAC.TOTL.CD              Net bilateral aid flows from DAC donors, Total (current US$)
DC.DAC.USAL.CD              Net bilateral aid flows from DAC donors, United States (current US$)
DC.ODA.TLDC.CD              Net ODA provided, to the least developed countries (current US$)
DC.ODA.TLDC.GN.ZS           Net ODA provided to the least developed countries (% of GNI)
DC.ODA.TOTL.CD              Net ODA provided, total (current US$)
DC.ODA.TOTL.GN.ZS           Net ODA provided, total (% of GNI)
DC.ODA.TOTL.KD              Net ODA provided, total (constant 2023 US$)
DT.DOD.DECT.CD              External debt stocks, total (DOD, current US$)
DT.DOD.DECT.GN.ZS           External debt stocks (% of GNI)
DT.DOD.DIMF.CD              Use of IMF credit (DOD, current US$)
DT.DOD.DLXF.CD              External debt stocks, long-term (DOD, current US$)
DT.DOD.DPNG.CD              External debt stocks, private nonguaranteed (PNG) (DOD, current US$)
DT.DOD.DPPG.CD              External debt stocks, public and publicly guaranteed (PPG) (DOD, current US$)
DT.DOD.DSTC.CD              External debt stocks, short-term (DOD, current US$)
DT.DOD.DSTC.IR.ZS           Short-term debt (% of total reserves)
DT.DOD.DSTC.XP.ZS           Short-term debt (% of exports of goods, services and primary income)
DT.DOD.DSTC.ZS              Short-term debt (% of total external debt)
DT.DOD.MIBR.CD              PPG, IBRD (DOD, current US$)
DT.DOD.MIDA.CD              PPG, IDA (DOD, current US$)
DT.DOD.MWBG.CD              IBRD loans and IDA credits (DOD, current US$)
DT.DOD.PVLX.CD              Present value of external debt (current US$)
DT.DOD.PVLX.EX.ZS           Present value of external debt (% of exports of goods, services and primary income)
DT.DOD.PVLX.GN.ZS           Present value of external debt (% of GNI)
DT.NFL.BLAT.CD              Net financial flows, bilateral (NFL, current US$)
DT.NFL.BOND.CD              Portfolio investment, bonds (PPG + PNG) (NFL, current US$)
DT.NFL.CERF.CD              Net official flows from UN agencies, CERF (current US$)
DT.NFL.DPNG.CD              Net flows on external debt, private nonguaranteed (PNG) (NFL, current US$)
DT.NFL.FAOG.CD              Net official flows from UN agencies, FAO (current US$)
DT.NFL.IAEA.CD              Net official flows from UN agencies, IAEA (current US$)
DT.NFL.IFAD.CD              Net official flows from UN agencies, IFAD (current US$)
DT.NFL.ILOG.CD              Net official flows from UN agencies, ILO (current US$)
DT.NFL.IMFC.CD              Net financial flows, IMF concessional (NFL, current US$)
DT.NFL.IMFN.CD              Net financial flows, IMF nonconcessional (NFL, current US$)
DT.NFL.MIBR.CD              Net financial flows, IBRD (NFL, current US$)
DT.NFL.MIDA.CD              Net financial flows, IDA (NFL, current US$)
DT.NFL.MLAT.CD              Net financial flows, multilateral (NFL, current US$)
DT.NFL.MOTH.CD              Net financial flows, others (NFL, current US$)
DT.NFL.NIFC.CD              IFC, private nonguaranteed (NFL, US$)
DT.NFL.OFFT.CD              PPG, official creditors (NFL, US$)
DT.NFL.PBND.CD              PPG, bonds (NFL, current US$)
DT.NFL.PCBK.CD              PPG, commercial banks (NFL, current US$)
DT.NFL.PCBO.CD              Commercial banks and other lending (PPG + PNG) (NFL, current US$)
DT.NFL.PNGB.CD              PNG, bonds (NFL, current US$)
DT.NFL.PNGC.CD              PNG, commercial banks and other creditors (NFL, current US$)
DT.NFL.PROP.CD              PPG, other private creditors (NFL, current US$)
DT.NFL.PRVT.CD              PPG, private creditors (NFL, US$)
DT.NFL.RDBC.CD              Net financial flows, RDB concessional (NFL, current US$)
DT.NFL.RDBN.CD              Net financial flows, RDB nonconcessional (NFL, current US$)
DT.NFL.SDGF.CD              Net official flows from UN agencies, SDGFUND (current US$)
DT.NFL.SPRP.CD              Net official flows from UN agencies, SPRP (current US$)
DT.NFL.UNAI.CD              Net official flows from UN agencies, UNAIDS (current US$)
DT.NFL.UNCD.CD              Net official flows from UN agencies, UNCDF (current US$)
DT.NFL.UNCF.CD              Net official flows from UN agencies, UNICEF (current US$)
DT.NFL.UNCR.CD              Net official flows from UN agencies, UNHCR (current US$)
DT.NFL.UNCTAD.CD            Net official flows from UN agencies, UNCTAD (current US$)
DT.NFL.UNCV.CD              Net official flows from UN agencies, UNCOVID (current US$)
DT.NFL.UNDP.CD              Net official flows from UN agencies, UNDP (current US$)
DT.NFL.UNEC.CD              Net official flows from UN agencies, UNECE (current US$)
DT.NFL.UNEP.CD              Net official flows from UN agencies, UNEP (current US$)
DT.NFL.UNFP.CD              Net official flows from UN agencies, UNFPA (current US$)
DT.NFL.UNID.CD              Net official flows from UN agencies, UNIDIR (current US$)
DT.NFL.UNIDO.CD             Net official flows from UN agencies, UNIDO (current US$)
DT.NFL.UNPB.CD              Net official flows from UN agencies, UNPBF (current US$)
DT.NFL.UNRW.CD              Net official flows from UN agencies, UNRWA (current US$)
DT.NFL.UNTA.CD              Net official flows from UN agencies, UNTA (current US$)
DT.NFL.UNWN.CD              Net official flows from UN agencies, UNWOMEN (current US$)
DT.NFL.UNWT.CD              Net official flows from UN agencies, UNWTO (current US$)
DT.NFL.WFPG.CD              Net official flows from UN agencies, WFP (current US$)
DT.NFL.WHOL.CD              Net official flows from UN agencies, WHO (current US$)
DT.NFL.WITC.CD              Net official flows from UN agencies, WTO-ITC (current US$)
DT.ODA.ALLD.CD              Net official development assistance and official aid received (current US$)
DT.ODA.ALLD.KD              Net official development assistance and official aid received (constant 2023 US$)
DT.ODA.OATL.CD              Net official aid received (current US$)
DT.ODA.OATL.KD              Net official aid received (constant 2023 US$)
DT.ODA.ODAT.CD              Net official development assistance received (current US$)
DT.ODA.ODAT.GI.ZS           Net ODA received (% of gross capital formation)
DT.ODA.ODAT.GN.ZS           Net ODA received (% of GNI)
DT.ODA.ODAT.KD              Net official development assistance received (constant 2023 US$)
DT.ODA.ODAT.MP.ZS           Net ODA received (% of imports of goods, services and primary income)
DT.ODA.ODAT.PC.ZS           Net ODA received per capita (current US$)
DT.ODA.ODAT.XP.ZS           Net ODA received (% of central government expense)
DT.TDS.DECT.CD              Debt service on external debt, total (TDS, current US$)
DT.TDS.DECT.EX.ZS           Total debt service (% of exports of goods, services and primary income)
DT.TDS.DECT.GN.ZS           Total debt service (% of GNI)
DT.TDS.DIMF.CD              IMF repurchases and charges (TDS, current US$)
DT.TDS.DPPF.XP.ZS           Debt service (PPG and IMF only, % of exports of goods, services and primary income)
DT.TDS.DPPG.CD              Debt service on external debt, public and publicly guaranteed (PPG) (TDS, current US$)
DT.TDS.DPPG.GN.ZS           Public and publicly guaranteed debt service (% of GNI)
DT.TDS.DPPG.XP.ZS           Public and publicly guaranteed debt service (% of exports of goods, services and primary income)
DT.TDS.MLAT.CD              Multilateral debt service (TDS, current US$)
DT.TDS.MLAT.PG.ZS           Multilateral debt service (% of public and publicly guaranteed debt service)
EG.CFT.ACCS.RU.ZS           Access to clean fuels and technologies for cooking, rural (% of rural population)
EG.CFT.ACCS.UR.ZS           Access to clean fuels and technologies for cooking, urban (% of urban population)
EG.CFT.ACCS.ZS              Access to clean fuels and technologies for cooking (% of population)
EG.EGY.PRIM.PP.KD           Energy intensity level of primary energy (MJ/$2021 PPP GDP)
EG.ELC.ACCS.RU.ZS           Access to electricity, rural (% of rural population)
EG.ELC.ACCS.UR.ZS           Access to electricity, urban (% of urban population)
EG.ELC.ACCS.ZS              Access to electricity (% of population)
EG.ELC.COAL.ZS              Electricity production from coal sources (% of total)
EG.ELC.FOSL.ZS              Electricity production from oil, gas and coal sources (% of total)
EG.ELC.HYRO.ZS              Electricity production from hydroelectric sources (% of total)
EG.ELC.LOSS.ZS              Electric power transmission and distribution losses (% of output)
EG.ELC.NGAS.ZS              Electricity production from natural gas sources (% of total)
EG.ELC.NUCL.ZS              Electricity production from nuclear sources (% of total)
EG.ELC.PETR.ZS              Electricity production from oil sources (% of total)
EG.ELC.RNEW.ZS              Renewable electricity output (% of total electricity output)
EG.ELC.RNWX.KH              Electricity production from renewable sources, excluding hydroelectric (kWh)
EG.ELC.RNWX.ZS              Electricity production from renewable sources, excluding hydroelectric (% of total)
EG.FEC.RNEW.ZS              Renewable energy consumption (% of total final energy consumption)
EG.GDP.PUSE.KO.PP           GDP per unit of energy use (PPP $ per kg of oil equivalent)
EG.GDP.PUSE.KO.PP.KD        GDP per unit of energy use (constant 2021 PPP $ per kg of oil equivalent)
EG.IMP.CONS.ZS              Energy imports, net (% of energy use)
EG.USE.COMM.CL.ZS           Alternative and nuclear energy (% of total energy use)
EG.USE.COMM.FO.ZS           Fossil fuel energy consumption (% of total)
EG.USE.COMM.GD.PP.KD        Energy use (kg of oil equivalent) per $1,000 GDP (constant 2021 PPP)
EG.USE.CRNW.ZS              Combustible renewables and waste (% of total energy)
EG.USE.ELEC.KH.PC           Electric power consumption (kWh per capita)
EG.USE.PCAP.KG.OE           Energy use (kg of oil equivalent per capita)
EN.ATM.PM25.MC.M3           PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)
EN.ATM.PM25.MC.T1.ZS        PM2.5 pollution, population exposed to levels exceeding WHO Interim Target-1 value (% of total)
EN.ATM.PM25.MC.T2.ZS        PM2.5 pollution, population exposed to levels exceeding WHO Interim Target-2 value (% of total)
EN.ATM.PM25.MC.T3.ZS        PM2.5 pollution, population exposed to levels exceeding WHO Interim Target-3 value (% of total)

Fortunately, this awesome package has a search string parameter to help us. Let's try it out.

In [105]:
wb.series.info(q="GDP per capita")

id                 value
-----------------  ---------------------------------------------------
NY.GDP.PCAP.CD     GDP per capita (current US$)
NY.GDP.PCAP.CN     GDP per capita (current LCU)
NY.GDP.PCAP.KD     GDP per capita (constant 2015 US$)
NY.GDP.PCAP.KD.ZG  GDP per capita growth (annual %)
NY.GDP.PCAP.KN     GDP per capita (constant LCU)
NY.GDP.PCAP.PP.CD  GDP per capita, PPP (current international $)
NY.GDP.PCAP.PP.KD  GDP per capita, PPP (constant 2021 international $)
                   7 elements

In [106]:
# 2. Search for CO2 emissions
wb.series.info(db=None, q="CO2")

id                          value
--------------------------  ------------------------------------------------------------------------------------------
EN.GHG.CO2.AG.MT.CE.AR5     Carbon dioxide (CO2) emissions from Agriculture (Mt CO2e)
EN.GHG.CO2.BU.MT.CE.AR5     Carbon dioxide (CO2) emissions from Building (Energy) (Mt CO2e)
EN.GHG.CO2.FE.MT.CE.AR5     Carbon dioxide (CO2) emissions from Fugitive Emissions (Energy) (Mt CO2e)
EN.GHG.CO2.IC.MT.CE.AR5     Carbon dioxide (CO2) emissions from Industrial Combustion (Energy) (Mt CO2e)
EN.GHG.CO2.IP.MT.CE.AR5     Carbon dioxide (CO2) emissions from Industrial Processes (Mt CO2e)
EN.GHG.CO2.LU.DF.MT.CE.AR5  Carbon dioxide (CO2) net fluxes from LULUCF - Deforestation (Mt CO2e)
EN.GHG.CO2.LU.FL.MT.CE.AR5  Carbon dioxide (CO2) net fluxes from LULUCF - Forest Land (Mt CO2e)
EN.GHG.CO2.LU.MT.CE.AR5     Carbon dioxide (CO2) net fluxes from LULUCF - Total excluding non-tropical fires (Mt CO2e)
EN.GHG.CO2.LU.OL.MT.CE.AR5  Carbon dioxide (CO2) net fluxes from LULUCF - Other Land (Mt CO2e)
EN.GHG.CO2.LU.OS.MT.CE.AR5  Carbon dioxide (CO2) net fluxes from LULUCF - Organic Soil (Mt CO2e)
EN.GHG.CO2.MT.CE.AR5        Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e)
EN.GHG.CO2.PC.CE.AR5        Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita)
EN.GHG.CO2.PI.MT.CE.AR5     Carbon dioxide (CO2) emissions from Power Industry (Energy) (Mt CO2e)
EN.GHG.CO2.TR.MT.CE.AR5     Carbon dioxide (CO2) emissions from Transport (Energy) (Mt CO2e)
EN.GHG.CO2.WA.MT.CE.AR5     Carbon dioxide (CO2) emissions from Waste (Mt CO2e)
EN.GHG.CO2.ZG.AR5           Carbon dioxide (CO2) emissions (total) excluding LULUCF (% change from 1990)
IC.FRM.CO2.ZS               Firms monitoring own CO2 emissions (% of firms)
                            17 elements

In [107]:
for row in wb.data.fetch("EN.GHG.CO2.PC.CE.AR5", "BRA"):
    print(row)

{'value': 2.31826466114939, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2024'}
{'value': 2.27447826989363, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2023'}
{'value': 2.27889577215227, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2022'}
{'value': 2.41580858865319, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2021'}
{'value': 2.1466461829, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2020'}
{'value': 2.25869881785082, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2019'}
{'value': 2.28562350357953, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2018'}
{'value': 2.41694955353585, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2017'}
{'value': 2.37533549789759, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2016'}
{'value': 2.56818858918394, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2015'}
{'value': 2.7310345760982, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2014'}
{'value': 2.63744450973958, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2013'}
{'value': 2.52901988702936, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2012'}
{'value': 2.37418967936326, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2011'}
{'value': 2.27112813109879, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2010'}
{'value': 2.00746250710986, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2009'}
{'value': 2.16839391882541, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2008'}
{'value': 2.08496718576573, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2007'}
{'value': 2.00204169117872, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2006'}
{'value': 1.99935674253319, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2005'}
{'value': 1.99978275095698, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2004'}
{'value': 1.91839410561756, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2003'}
{'value': 1.96879630651915, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2002'}
{'value': 1.9928207750233, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2001'}
{'value': 2.00787868943563, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR2000'}
{'value': 1.95707166300643, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1999'}
{'value': 1.94230001237588, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1998'}
{'value': 1.91554735453581, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1997'}
{'value': 1.83087535382901, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1996'}
{'value': 1.73140553131602, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1995'}
{'value': 1.62465005024393, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1994'}
{'value': 1.59016787933935, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1993'}
{'value': 1.54720906025269, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1992'}
{'value': 1.55060704334579, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1991'}
{'value': 1.52128199616552, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1990'}
{'value': 1.57652569669372, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1989'}
{'value': 1.58361516450006, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1988'}
{'value': 1.57986881026649, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1987'}
{'value': 1.56812051667974, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1986'}
{'value': 1.46143622805921, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1985'}
{'value': 1.39269321648948, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1984'}
{'value': 1.39937046188824, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1983'}
{'value': 1.49159229456595, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1982'}
{'value': 1.54175243182081, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1981'}
{'value': 1.70879909777171, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1980'}
{'value': 1.75182599890906, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1979'}
{'value': 1.67993440745492, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1978'}
{'value': 1.59110374660205, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1977'}
{'value': 1.55992356243525, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1976'}
{'value': 1.45405716888003, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1975'}
{'value': 1.38930108975977, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1974'}
{'value': 1.31786270727093, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1973'}
{'value': 1.16092679429378, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1972'}
{'value': 1.09248305949646, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1971'}
{'value': 1.12333492748584, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1970'}
{'value': None, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1969'}
{'value': None, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1968'}
{'value': None, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1967'}
{'value': None, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1966'}
{'value': None, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1965'}
{'value': None, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1964'}
{'value': None, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1963'}
{'value': None, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1962'}
{'value': None, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1961'}
{'value': None, 'series': 'EN.GHG.CO2.PC.CE.AR5', 'economy': 'BRA', 'aggregate': False, 'time': 'YR1960'}

In [108]:
wb.data.DataFrame(["EN.GHG.CO2.PC.CE.AR5", "NY.GDP.PCAP.PP.CD"], "BRA", mrv=10)

,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,YR2023,YR2024
series,,,,,,,,,,
EN.GHG.CO2.PC.CE.AR5,2.568189,2.375335,2.41695,2.285624,2.258699,2.146646,2.415809,2.278896,2.274478,2.318265
NY.GDP.PCAP.PP.CD,14821.438318,14309.206149,14559.04889,15463.742639,16069.838015,16101.618306,18075.706005,19876.853353,21175.618699,22338.476564

Great! We've identified our series. We need to work with:
- `NY.GDP.PCAP.PP.CD` –	GDP per capita, PPP (current international $)
- `EN.GHG.CO2.PC.CE.AR5` – Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita)

### 1.1.1 Fetch and Clean Data
First, we'll define our indicators. We map the complex codes to simpler names.

In [109]:
indicators = {
    "NY.GDP.PCAP.PP.CD": "GDP_PPP",
    "EN.GHG.CO2.PC.CE.AR5": "CO2_Capita"
}

Then, we can fetch data for the last 10 years. That should suffice.

In [110]:
df_raw = wb.data.DataFrame(indicators,
                           economy="all",
                           time=range(2014, 2025),
                           skipAggs=True, # Remove regional/world aggregates
                           numericTimeKeys=True, # Return years as integers
                           labels=True, # Add Country Column name
                           columns="series"
                           )

In [111]:
df_raw.head()

               Country  Time  EN.GHG.CO2.PC.CE.AR5  NY.GDP.PCAP.PP.CD
economy time
ZWE     2024  Zimbabwe  2024              0.772821        5928.080625
        2023  Zimbabwe  2023              0.768994        5791.192129
        2022  Zimbabwe  2022              0.719221        5395.856298
        2021  Zimbabwe  2021              0.688925        4827.088694
        2020  Zimbabwe  2020              0.584444        4178.585579

In [112]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2387 entries, ('ZWE', np.int64(2024)) to ('AFG', np.int64(2014))
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country               2387 non-null   object
 1   Time                  2387 non-null   object
 2   EN.GHG.CO2.PC.CE.AR5  2233 non-null   float64
 3   NY.GDP.PCAP.PP.CD     2175 non-null   float64
dtypes: float64(2), object(2)
memory usage: 156.4+ KB

Awesome! Now, we need to clean the index/columns.

In [113]:
df = df_raw.reset_index()
df

     economy  time      Country  Time  EN.GHG.CO2.PC.CE.AR5  NY.GDP.PCAP.PP.CD
0        ZWE  2024     Zimbabwe  2024              0.772821        5928.080625
1        ZWE  2023     Zimbabwe  2023              0.768994        5791.192129
2        ZWE  2022     Zimbabwe  2022              0.719221        5395.856298
3        ZWE  2021     Zimbabwe  2021              0.688925        4827.088694
4        ZWE  2020     Zimbabwe  2020              0.584444        4178.585579
...      ...   ...          ...   ...                   ...                ...
2382     AFG  2018  Afghanistan  2018              0.321419        2432.276701
2383     AFG  2017  Afghanistan  2017              0.291328        2335.795862
2384     AFG  2016  Afghanistan  2016              0.219353        2213.181441
2385     AFG  2015  Afghanistan  2015              0.249091        2284.075848
2386     AFG  2014  Afghanistan  2014              0.242702        2224.490748

[2387 rows x 6 columns]

Our dictionary values were not passed as column names. Let's try to fix that as well.

In [114]:
df = df.rename(columns=indicators)

In [115]:
df

     economy  time      Country  Time  CO2_Capita      GDP_PPP
0        ZWE  2024     Zimbabwe  2024    0.772821  5928.080625
1        ZWE  2023     Zimbabwe  2023    0.768994  5791.192129
2        ZWE  2022     Zimbabwe  2022    0.719221  5395.856298
3        ZWE  2021     Zimbabwe  2021    0.688925  4827.088694
4        ZWE  2020     Zimbabwe  2020    0.584444  4178.585579
...      ...   ...          ...   ...         ...          ...
2382     AFG  2018  Afghanistan  2018    0.321419  2432.276701
2383     AFG  2017  Afghanistan  2017    0.291328  2335.795862
2384     AFG  2016  Afghanistan  2016    0.219353  2213.181441
2385     AFG  2015  Afghanistan  2015    0.249091  2284.075848
2386     AFG  2014  Afghanistan  2014    0.242702  2224.490748

[2387 rows x 6 columns]

We can now drop wors where GDP or CO2 is missing.

In [116]:
df.isnull().sum()

economy         0
time            0
Country         0
Time            0
CO2_Capita    154
GDP_PPP       212
dtype: int64

In [117]:
df_complete = df.dropna(subset=["GDP_PPP", "CO2_Capita"])
df_complete.sample(5)

     economy  time             Country  Time  CO2_Capita        GDP_PPP
1614     GAB  2016               Gabon  2016    3.122878   13997.735284
448      SOM  2016  Somalia, Fed. Rep.  2016    0.058388    1468.504385
2044     BDI  2015             Burundi  2015    0.039375     722.032898
2147     BMU  2022             Bermuda  2022    3.976895  105142.409967
1406     IND  2015               India  2015    1.715503    5425.035991

Now, we can sort our DataFrame. Later on, we'll keep the most recent year per country.

In [118]:
df_final = df_complete.sort_values(["Country", "time"], ascending=[True, False])
df_final.head()

     economy  time      Country  Time  CO2_Capita      GDP_PPP
2377     AFG  2023  Afghanistan  2023    0.280995  2201.722907
2378     AFG  2022  Afghanistan  2022    0.278421  2122.995815
2379     AFG  2021  Afghanistan  2021    0.312157  2144.166570
2380     AFG  2020  Afghanistan  2020    0.310825  2561.981761
2381     AFG  2019  Afghanistan  2019    0.319753  2583.485332

In [119]:
df_final = df_final.rename(columns={
    "economy": "Country_ISO",
    "Time": "Year"})

In [120]:
df_final = df_final.drop(columns="time").reset_index(drop=True)
df_final

     Country_ISO      Country  Year  CO2_Capita       GDP_PPP
0            AFG  Afghanistan  2023    0.280995   2201.722907
1            AFG  Afghanistan  2022    0.278421   2122.995815
2            AFG  Afghanistan  2021    0.312157   2144.166570
3            AFG  Afghanistan  2020    0.310825   2561.981761
4            AFG  Afghanistan  2019    0.319753   2583.485332
...          ...          ...   ...         ...           ...
2081         ZWE     Zimbabwe  2018    0.816285   3992.890719
2082         ZWE     Zimbabwe  2017    0.714789  10756.445442
2083         ZWE     Zimbabwe  2016    0.771813   4275.449351
2084         ZWE     Zimbabwe  2015    0.881442   4045.898647
2085         ZWE     Zimbabwe  2014    0.886871   3903.427977

[2086 rows x 5 columns]

### 1.1.2 Keep Latest Data
For our analysis, we'll want to work with the latest data available for each country only.

In [121]:
df_final = df_final.drop_duplicates(subset="Country_ISO", keep="first")
df_final

,Country_ISO,Country,Year,CO2_Capita,GDP_PPP
0,AFG,Afghanistan,2023,0.280995,2201.722907
10,ALB,Albania,2024,1.785221,26693.193437
21,DZA,Algeria,2024,3.980800,17620.742396
32,AGO,Angola,2024,0.741712,10118.608995
43,ATG,Antigua and Barbuda,2024,3.798575,33386.191713
54,ARG,Argentina,2024,4.010665,30431.193122
65,ARM,Armenia,2024,2.470282,22823.179526
76,ABW,Aruba,2024,5.148386,50649.301523
87,AUS,Australia,2024,14.097354,71410.419875
98,AUT,Austria,2024,6.322784,71621.803364
109,AZE,Azerbaijan,2024,3.811443,25088.999376
120,BHS,"Bahamas, The",2024,3.636336,41197.934255
131,BHR,Bahrain,2024,23.899992,66941.243037
142,BGD,Bangladesh,2024,0.715539,9646.769844
153,BRB,Barbados,2024,2.523481,24822.534331
164,BLR,Belarus,2024,5.936494,33010.330761
175,BEL,Belgium,2024,7.306615,72236.905055
186,BLZ,Belize,2024,0.932453,14346.518805
197,BEN,Benin,2024,0.487329,4434.564218
208,BMU,Bermuda,2024,4.135466,124252.835703
219,BTN,Bhutan,2023,1.984651,16215.152007
229,BOL,Bolivia,2024,2.290734,12877.635118
240,BIH,Bosnia and Herzegovina,2024,6.449358,22955.761620
251,BWA,Botswana,2024,2.737493,20538.132018
262,BRA,Brazil,2024,2.318265,22338.476564
273,BRN,Brunei Darussalam,2024,20.242652,89879.361498
284,BGR,Bulgaria,2024,5.307602,41519.539790
295,BFA,Burkina Faso,2024,0.274991,2895.891520
306,BDI,Burundi,2024,0.068957,1194.946814
317,CPV,Cabo Verde,2024,1.288302,11195.120531
328,KHM,Cambodia,2024,1.102070,7966.873524
339,CMR,Cameroon,2024,0.353420,5588.986459
350,CAN,Canada,2024,13.998358,65463.099099
361,CYM,Cayman Islands,2023,4.920726,88427.786671
371,CAF,Central African Republic,2024,0.063294,1263.102342
382,TCD,Chad,2024,0.142509,2742.659522
393,CHL,Chile,2024,3.937440,34637.116828
404,CHN,China,2024,9.315089,27104.870268
415,COL,Colombia,2024,1.797804,21508.780248
426,COM,Comoros,2024,0.514985,3958.532288
437,COD,"Congo, Dem. Rep.",2024,0.056825,1821.048687
448,COG,"Congo, Rep.",2024,1.335363,7026.362233
459,CRI,Costa Rica,2024,1.632836,30062.849160
470,CIV,Cote d'Ivoire,2024,0.589054,7669.231957
481,HRV,Croatia,2024,4.831514,48816.948003
492,CYP,Cyprus,2024,5.404695,61271.820312
503,CZE,Czechia,2024,7.129665,56686.545349
514,DNK,Denmark,2024,4.278205,79514.285438
525,DJI,Djibouti,2024,0.765537,7810.278691
536,DMA,Dominica,2024,1.273318,21300.684870
547,DOM,Dominican Republic,2024,2.994735,27541.662528
558,ECU,Ecuador,2024,2.644750,15840.266857
569,EGY,"Egypt, Arab Rep.",2024,2.502514,19094.144944
580,SLV,El Salvador,2024,1.505697,13264.027091
591,GNQ,Equatorial Guinea,2024,2.550520,17566.760028
602,EST,Estonia,2024,7.759369,49321.045005
613,SWZ,Eswatini,2024,0.880335,11799.202879
624,ETH,Ethiopia,2024,0.146637,3287.534922
635,FRO,Faroe Islands,2024,0.038405,81908.778179
646,FJI,Fiji,2024,1.622229,15450.299327
657,FIN,Finland,2024,5.535212,64288.554014
668,FRA,France,2024,4.003558,61290.423825
679,GAB,Gabon,2024,2.047498,21510.172531
690,GMB,"Gambia, The",2024,0.178370,3475.612457
701,GEO,Georgia,2024,3.640274,28285.073280
712,DEU,Germany,2024,6.943957,72295.235373
723,GHA,Ghana,2024,0.702086,8019.997024
734,GRC,Greece,2024,5.046422,44005.128932
745,GRL,Greenland,2023,10.285765,78840.597840
755,GRD,Grenada,2024,1.500764,20177.809493
766,GTM,Guatemala,2024,1.106650,14368.660568
777,GIN,Guinea,2024,0.352794,4565.300789
788,GNB,Guinea-Bissau,2024,0.155450,3119.371570
799,GUY,Guyana,2024,4.558608,80155.039393
810,HTI,Haiti,2024,0.298474,3193.671364
821,HND,Honduras,2024,1.135520,7486.018696
832,HKG,"Hong Kong SAR, China",2024,4.600710,75195.986597
843,HUN,Hungary,2024,4.457918,47637.135988
854,ISL,Iceland,2024,8.519919,81924.411472
865,IND,India,2024,2.173652,11159.985648
876,IDN,Indonesia,2024,2.865040,16448.275518
887,IRN,"Iran, Islamic Rep.",2024,9.053293,19873.886085
898,IRQ,Iraq,2024,5.183752,14464.318693
909,IRL,Ireland,2024,6.036058,130797.489687
920,ISR,Israel,2024,5.781340,55690.739103
931,ITA,Italy,2024,5.075738,60881.372639
942,JAM,Jamaica,2024,2.843784,12890.266005
953,JPN,Japan,2024,7.842421,51685.038753
964,JOR,Jordan,2024,2.089869,10821.490977
975,KAZ,Kazakhstan,2024,12.567819,40890.931769
986,KEN,Kenya,2024,0.383441,6644.130932
997,KIR,Kiribati,2024,0.592486,3702.325947
1008,KOR,"Korea, Rep.",2024,11.362257,58894.997574
1019,KWT,Kuwait,2024,23.672672,52443.596922
1030,KGZ,Kyrgyz Republic,2024,1.487842,8012.454644
1041,LAO,Lao PDR,2024,3.354351,9775.828174
1052,LVA,Latvia,2024,3.647775,43780.383023
1063,LBN,Lebanon,2023,1.873874,12574.832912
1073,LSO,Lesotho,2024,0.428078,3001.163120
1084,LBR,Liberia,2024,0.154486,1871.044062
1095,LBY,Libya,2024,8.664571,14303.808774
1106,LTU,Lithuania,2024,4.490565,54409.762840
1117,LUX,Luxembourg,2024,10.557272,150929.364203
1128,MAC,"Macao SAR, China",2024,2.525328,126959.917139
1139,MDG,Madagascar,2024,0.146495,1883.537431
1150,MWI,Malawi,2024,0.221419,1857.617570
1161,MYS,Malaysia,2024,8.323216,38779.283044
1172,MDV,Maldives,2024,3.566509,26182.783157
1183,MLI,Mali,2024,0.302799,3314.773322
1194,MLT,Malta,2024,3.178886,69832.187101
1205,MHL,Marshall Islands,2024,0.002663,8194.638548
1216,MRT,Mauritania,2024,0.969475,7368.752753
1227,MUS,Mauritius,2024,3.536342,31839.759754
1238,MEX,Mexico,2024,3.637387,25738.603144
1249,FSM,"Micronesia, Fed. Sts.",2024,0.001767,4346.842497
1260,MDA,Moldova,2024,3.416759,18614.988069
1271,MNG,Mongolia,2024,7.846656,19144.726137
1282,MAR,Morocco,2024,1.839253,10415.124023
1293,MOZ,Mozambique,2024,0.292006,1705.379195
1304,MMR,Myanmar,2024,0.575463,5997.465163
1315,NAM,Namibia,2024,1.204502,11686.602066
1326,NRU,Nauru,2024,0.000000,14173.008104
1337,NPL,Nepal,2024,0.535964,5736.621343
1348,NLD,Netherlands,2024,6.601884,84221.978378
1359,NZL,New Zealand,2024,6.016946,55624.934722
1370,NIC,Nicaragua,2024,0.829842,8708.799831
1381,NER,Niger,2024,0.118902,2049.933053
1392,NGA,Nigeria,2024,0.566918,9086.875506
1403,MKD,North Macedonia,2024,3.999925,26536.048513
1414,NOR,Norway,2024,7.178302,101031.460599
1425,OMN,Oman,2024,18.651991,41740.165853
1436,PAK,Pakistan,2024,0.811832,6252.115432
1447,PLW,Palau,2023,78.857111,18230.269863
1457,PAN,Panama,2024,2.738299,41369.422541
1468,PNG,Papua New Guinea,2024,0.516967,4874.689955
1479,PRY,Paraguay,2024,1.158194,18523.681015
1490,PER,Peru,2024,2.024242,17802.418250
1501,PHL,Philippines,2024,1.503011,11794.137549
1512,POL,Poland,2024,7.551086,50540.932080
1523,PRT,Portugal,2024,3.324765,50649.510238
1534,PRI,Puerto Rico (US),2024,4.816946,50247.849246
1545,QAT,Qatar,2024,47.332164,126046.354856
1556,ROU,Romania,2024,3.720551,48731.324910
1567,RUS,Russian Federation,2024,13.997772,47404.964844
1578,RWA,Rwanda,2024,0.162129,3710.860404
1589,WSM,Samoa,2024,1.604447,8736.816068
1600,STP,Sao Tome and Principe,2024,0.627080,6241.856145
1611,SAU,Saudi Arabia,2024,18.484584,71375.372789
1622,SEN,Senegal,2024,0.767610,5070.648621
1633,SYC,Seychelles,2024,7.236679,33238.580034
1644,SLE,Sierra Leone,2024,0.169150,3522.305880
1655,SGP,Singapore,2024,9.751444,150689.301626
1666,SVK,Slovak Republic,2024,5.513117,47180.848766
1677,SVN,Slovenia,2024,6.266523,56502.037524
1688,SLB,Solomon Islands,2024,0.383912,2674.893113
1699,SOM,"Somalia, Fed. Rep.",2024,0.045515,1601.964666
1710,ZAF,South Africa,2024,6.876850,15456.198993
1721,ESP,Spain,2024,4.505407,56877.641103
1732,LKA,Sri Lanka,2024,1.064734,15632.592485
1743,KNA,St. Kitts and Nevis,2024,2.884102,34846.603534
1754,LCA,St. Lucia,2024,1.710766,27567.328078
1765,VCT,St. Vincent and the Grenadines,2024,1.311919,21272.080067
1776,SDN,Sudan,2024,0.433464,2115.816162
1787,SUR,Suriname,2024,4.061119,21800.526599
1798,SWE,Sweden,2024,3.573816,71030.460172
1809,CHE,Switzerland,2024,3.745688,94115.824262
1820,SYR,Syrian Arab Republic,2022,1.387470,4772.461677
1826,TJK,Tajikistan,2024,0.922478,5405.980116
1837,TZA,Tanzania,2024,0.311206,4220.796387
1848,THA,Thailand,2024,3.960053,24712.065858
1859,TLS,Timor-Leste,2024,0.499344,4422.778822
1870,TGO,Togo,2024,0.276147,3365.458090
1881,TON,Tonga,2023,1.546889,7802.669862
1891,TTO,Trinidad and Tobago,2024,19.581052,36328.513007
1902,TUN,Tunisia,2024,2.621130,14521.008094
1913,TUR,Turkiye,2024,5.379265,45122.931719
1924,TKM,Turkmenistan,2024,10.862369,21213.086250
1935,TCA,Turks and Caicos Islands,2024,4.923176,37954.387654
1946,TUV,Tuvalu,2023,0.000000,6151.010470
1956,UGA,Uganda,2024,0.165048,3273.267174
1967,UKR,Ukraine,2024,3.129348,18550.462891
1978,ARE,United Arab Emirates,2024,18.255206,79228.738801
1989,GBR,United Kingdom,2024,4.224127,60620.380775
2000,USA,United States,2024,13.619569,85809.900385
2011,URY,Uruguay,2024,2.567569,36417.874162
2022,UZB,Uzbekistan,2024,4.085017,11878.552871
2033,VUT,Vanuatu,2024,0.869799,3605.607367
2044,VNM,Viet Nam,2024,4.266057,16385.506557
2055,VIR,Virgin Islands (U.S.),2022,0.001897,49793.032440
2064,ZMB,Zambia,2024,0.542961,4214.892778
2075,ZWE,Zimbabwe,2024,0.772821,5928.080625

In [123]:
print(f"Columns fixed: {df_final.columns.tolist()}")
print(df_final.head())

Columns fixed: ['Country_ISO', 'Country', 'Year', 'CO2_Capita', 'GDP_PPP']
   Country_ISO              Country  Year  CO2_Capita       GDP_PPP
0          AFG          Afghanistan  2023    0.280995   2201.722907
10         ALB              Albania  2024    1.785221  26693.193437
21         DZA              Algeria  2024    3.980800  17620.742396
32         AGO               Angola  2024    0.741712  10118.608995
43         ATG  Antigua and Barbuda  2024    3.798575  33386.191713

Awesome! We can move on to our next step.
# 2. Divide countries into two groups by their GDP per capita and calculate the average difference in CO2 emission per capita between the two groups.
## 2.1 Grouping countries by GDP
First, we need to define a cutoff line to divide our countries. We can use the median GDP.

In [124]:
median_gdp  = df_final["GDP_PPP"].median()
print(f"The cutoff line (Median GDP) is : ${median_gdp:.2f}")

The cutoff line (Median GDP) is : $19873.89

Ok! Now we can create our groups based on this median.

In [125]:
# Use .copy() to avoid warnings
df_final = df_final.copy()
df_final["Group"] = np.where(df_final["GDP_PPP"] > median_gdp, "Rich", "Poor")

In [126]:
df_final.sample(10)

     Country_ISO              Country  Year  CO2_Capita       GDP_PPP Group
975          KAZ           Kazakhstan  2024   12.567819  40890.931769  Rich
1227         MUS            Mauritius  2024    3.536342  31839.759754  Rich
920          ISR               Israel  2024    5.781340  55690.739103  Rich
953          JPN                Japan  2024    7.842421  51685.038753  Rich
175          BEL              Belgium  2024    7.306615  72236.905055  Rich
1946         TUV               Tuvalu  2023    0.000000   6151.010470  Poor
2033         VUT              Vanuatu  2024    0.869799   3605.607367  Poor
1881         TON                Tonga  2023    1.546889   7802.669862  Poor
1348         NLD          Netherlands  2024    6.601884  84221.978378  Rich
43           ATG  Antigua and Barbuda  2024    3.798575  33386.191713  Rich

## 2.1 Calculate the average difference in CO2 emission per capita between the two groups

In [128]:
group_stats = df_final.groupby(by="Group")["CO2_Capita"].mean()
group_stats

Group
Poor    2.210134
Rich    6.847820
Name: CO2_Capita, dtype: float64

We can see that the average CO2 emissions per capita is quite different between the two groups. Let's see the average difference now.

In [129]:
actual_diff = group_stats["Rich"] - group_stats["Poor"]
print(f"Rich countries emit {actual_diff:.2f} tons more.")

Rich countries emit 4.64 tons more.